name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install and Build
        run: |
          npm i
          npm run build:prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.SECRETS_DEPLOY }}
          publish_dir: ./dist
  
      
